IDIOMA_ACTUAL = "es"

TEXTOS = {
    "es": {
        "titulo": "Sentinel System — Panel Principal",
        "salir": "← Salir",
        "inicio": "Inicio",
        "nuevo": "Nuevo Registro",
        "info": "Información Escolar",
        "historial": "Historial de Accesos",
        "pantalla": "Pantalla de Accesos",
        "bienvenida": "Le da la Bienvenida al Sistema",
        "seleccion": "Seleccione una opción del menú para comenzar",
        "agregar": "➕  Agregar nuevo usuario",
        "iniciar": "▶  Iniciar",
        "detener": "⏹  Detener",
        "camara_on": "⬤  Cámara en línea",
        "camara_off": "⬤  Cámara apagada",
        "navegacion": "NAVEGACIÓN",
        "control_accesos": "Control de Accesos",
        "esperando": "Esperando reconocimiento",
        "colocate": "Colócate frente a la cámara",
        "presiona_iniciar": "Presiona ▶ Iniciar para comenzar",
        "iniciando_camara": "Iniciando cámara",
        "preparando": "Preparando reconocimiento facial...",
        "confirmar_salida": "Confirmar salida",
        "seguro_salir": "¿Estás seguro de que deseas salir?",
                "info_escolar": "Información Escolar",
        "gestion_usuarios": "Gestión de usuarios registrados en el sistema",
        "ver_detalles": "Ver detalles",
        "buscar": "Buscar:",
        "placeholder_busqueda": "Nombre, matrícula o carrera...",
        "usuarios_registrados": "Usuarios registrados",
        "nombre_completo": "Nombre Completo",
        "matricula": "Matrícula",
        "rol": "Rol",
        "editar": "Editar",
        "eliminar": "Eliminar",
        "error": "Error",
        "error_db": "No se pudo conectar a la base de datos",
        "detalles": "Detalles",
        "selecciona_usuario": "Selecciona un usuario",
        "atencion": "Atención",
        "editar_usuario": "Editar Usuario",
        "datos_personales": "Datos personales",
        "guardar": "Guardar",
        "retomar_fotos": "Retomar fotos",
        "cancelar": "Cancelar",
        "confirmar_eliminacion": "Confirmar eliminación",
        "papelera": "Papelera de Usuarios",
        "papelera_usuarios": "Papelera — Usuarios Inactivos",
        "restaurar_usuario": "Restaurar Usuario",
        "ocultar_detalles": "Ocultar detalles",
        "nombre": "Nombre",
        "apellido_paterno": "Apellido Paterno",
        "apellido_materno": "Apellido Materno",
        "telefono": "Teléfono",
        "facultad": "Facultad",
        "carrera": "Carrera",
        "grado": "Grado",
        "grupo": "Grupo",
        "materia": "Materia",
        "puesto": "Puesto",
        "area": "Área",
        "grado_imparte": "Grado que imparte",
        "info_academica": "Información académica",
        "info_docente": "Información docente",
        "info_laboral": "Información laboral",
        "campos_obligatorios": "Campos obligatorios",
        "error_nombre": "Nombre y apellido paterno son obligatorios",
        "actualizado": "Actualizado",
        "usuario_actualizado": "Usuario actualizado correctamente",
        "no_actualizar": "No se pudo actualizar",
        "eliminado": "Eliminado",
        "usuario_eliminado": "Usuario eliminado correctamente",
        "confirmar": "Confirmar",
        "pregunta_eliminar": "¿Eliminar a {nombre} ({rol})?",
        "pregunta_restaurar": "¿Restaurar este usuario?",
        "restaurado": "Restaurado",
        "usuario_restaurado": "Usuario restaurado correctamente"
    },
    "en": {
        "titulo": "Sentinel System — Main Panel",
        "salir": "← Logout",
        "inicio": "Home",
        "nuevo": "New Register",
        "info": "School Info",
        "historial": "Access History",
        "pantalla": "Access Screen",
        "bienvenida": "Welcome to the System",
        "seleccion": "Select an option from the menu",
        "agregar": "➕  Add new user",
        "iniciar": "▶  Start",
        "detener": "⏹  Stop",
        "camara_on": "⬤  Camera online",
        "camara_off": "⬤  Camera off",
        "navegacion": "NAVIGATION",
        "control_accesos": "Access Control",
        "esperando": "Waiting for recognition",
        "colocate": "Stand in front of the camera",
        "presiona_iniciar": "Press ▶ Start to begin",
        "iniciando_camara": "Starting camera",
        "preparando": "Preparing facial recognition...",
        "confirmar_salida": "Confirm exit",
        "seguro_salir": "Are you sure you want to exit?",
        "info_escolar": "School Information",
        "gestion_usuarios": "Management of registered users in the system",
        "ver_detalles": "View details",
        "buscar": "Search:",
        "placeholder_busqueda": "Name, ID or major...",
        "usuarios_registrados": "Registered users",
        "nombre_completo": "Full Name",
        "matricula": "Student ID",
        "rol": "Role",
        "editar": "Edit",
        "eliminar": "Delete",
        "error": "Error",
        "error_db": "Could not connect to the database",
        "detalles": "Details",
        "selecciona_usuario": "Select a user",
        "atencion": "Warning",
        "editar_usuario": "Edit User",
        "datos_personales": "Personal Information",
        "guardar": "Save",
        "retomar_fotos": "Retake photos",
        "cancelar": "Cancel",
        "confirmar_eliminacion": "Confirm deletion",
        "papelera": "User Trash",
        "papelera_usuarios": "Trash — Inactive Users",
        "restaurar_usuario": "Restore User",
        "ocultar_detalles": "Hide details",
        "nombre": "Name",
        "apellido_paterno": "Last Name",
        "apellido_materno": "Second Last Name",
        "telefono": "Phone",
        "facultad": "Faculty",
        "carrera": "Major",
        "grado": "Grade",
        "grupo": "Group",
        "materia": "Subject",
        "puesto": "Position",
        "area": "Area",
        "grado_imparte": "Grade taught",
        "info_academica": "Academic Information",
        "info_docente": "Teacher Information",
        "info_laboral": "Work Information",
        "campos_obligatorios": "Required fields",
        "error_nombre": "Name and last name are required",
        "actualizado": "Updated",
        "usuario_actualizado": "User updated successfully",
        "no_actualizar": "Could not update",
        "eliminado": "Deleted",
        "usuario_eliminado": "User deleted successfully",
        "confirmar": "Confirm",
        "pregunta_eliminar": "Delete {nombre} ({rol})?",
        "pregunta_restaurar": "Restore this user?",
        "restaurado": "Restored",
        "usuario_restaurado": "User restored successfully"
    }
}

def t(clave):
    return TEXTOS[IDIOMA_ACTUAL].get(clave, clave)

def cambiar_idioma():
    global IDIOMA_ACTUAL
    IDIOMA_ACTUAL = "en" if IDIOMA_ACTUAL == "es" else "es"