IDIOMA_ACTUAL = "es"

TEXTOS = {
    "es": {
        "titulo": "Panel Principal",
        "salir": "← Salir",
        "inicio": "Inicio",
        "nuevo": "Nuevo Registro",
        "info": "Información Escolar",
        "historial": "Historial de Accesos",
        "pantalla": "Pantalla de Accesos",
        "bienvenida": "Le da la Bienvenida al Sistema",
        "seleccion": "Seleccione una opción del menú para comenzar",
        "agregar": "➕  Agregar nuevo usuario",
        "iniciar": "▶  Iniciar",
        "detener": "⏹  Detener",
        "camara_on": "⬤  Cámara en línea",
        "camara_off": "⬤  Cámara apagada",
        "navegacion": "NAVEGACIÓN",
        "control_accesos": "Control de Accesos",
        "esperando": "Esperando reconocimiento",
        "colocate": "Colócate frente a la cámara",
        "presiona_iniciar": "Presiona ▶ Iniciar para comenzar",
        "iniciando_camara": "Iniciando cámara",
        "preparando": "Preparando reconocimiento facial...",
        "confirmar_salida": "Confirmar salida",
        "seguro_salir": "¿Estás seguro de que deseas salir?",
                "info_escolar": "Información Escolar",
        "gestion_usuarios": "Gestión de usuarios registrados en el sistema",
        "ver_detalles": "Ver detalles",
        "buscar": "Buscar:",
        "placeholder_busqueda": "Nombre, matrícula o carrera...",
        "usuarios_registrados": "Usuarios registrados",
        "nombre_completo": "Nombre Completo",
        "matricula": "Número de control",
        "rol": "Rol",
        "editar": "Editar",
        "eliminar": "Eliminar",
        "error": "Error",
        "error_db": "No se pudo conectar a la base de datos",
        "detalles": "Detalles",
        "detalles_acceso": "Detalles del acceso",
        "selecciona_usuario": "Selecciona un usuario",
        "atencion": "Atención",
        "editar_usuario": "Editar Usuario",
        "datos_personales": "Datos personales",
        "guardar": "Guardar",
        "retomar_fotos": "Retomar fotos",
        "cancelar": "Cancelar",
        "confirmar_eliminacion": "Confirmar eliminación",
        "papelera": "Papelera de Usuarios",
        "papelera_usuarios": "Papelera — Usuarios Inactivos",
        "restaurar_usuario": "Restaurar Usuario",
        "ocultar_detalles": "Ocultar detalles",
        "nombre": "Nombre",
        "apellido_paterno": "Primer apellido",
        "apellido_materno": "Segundo apellido",
        "telefono": "Teléfono",
        "facultad": "Facultad",
        "carrera": "Carrera",
        "grado": "Grado",
        "grupo": "Grupo",
        "materia": "Materia",
        "puesto": "Puesto",
        "area": "Área",
        "grado_imparte": "Grado que imparte",
        "info_academica": "Información académica",
        "info_docente": "Información docente",
        "info_laboral": "Información laboral",
        "campos_obligatorios": "Campos obligatorios",
        "error_nombre": "Nombre y apellido paterno son obligatorios",
        "actualizado": "Actualizado",
        "usuario_actualizado": "Usuario actualizado correctamente",
        "no_actualizar": "No se pudo actualizar",
        "eliminado": "Eliminado",
        "usuario_eliminado": "Usuario eliminado correctamente",
        "confirmar": "Confirmar",
        "pregunta_eliminar": "¿Eliminar a {nombre} ({rol})?",
        "pregunta_restaurar": "¿Restaurar este usuario?",
        "restaurado": "Restaurado",
        "usuario_restaurado": "Usuario restaurado correctamente",
         "estudiante": "Estudiante",
        "docente": "Docente",
        "personal": "Personal",
        "nuevo_registro_titulo": "Nuevo Registro",
        "selecciona_tipo_usuario": "Selecciona el tipo de usuario",
        "seleccionar": "Seleccionar",
        "regresar": "Regresar",
        "paso_datos": "Paso 1: Captura de datos",
        "continuar_fotos": "Continuar a Fotos",
        "datos_personales": "Datos Personales",
        "info_academica": "Información Académica",
        "info_docente": "Información Docente",
        "info_laboral": "Información Laboral",
        "nombre": "Nombre",
        "apellido_paterno": "Primer apellido",
        "apellido_materno": "Segundo apellido",
        "matricula": "Número de control",
        "telefono": "Teléfono",
        "correo": "Correo Electrónico",
        "fecha_nacimiento": "Fecha de Nacimiento",
        "tipo_sangre": "Tipo de Sangre",
        "direccion": "Dirección",
        "grado": "Grado",
        "grupo": "Grupo",
        "facultad": "Facultad",
        "carrera": "Carrera",
        "grado_imparte": "Grado que imparte",
        "materia": "Materia",
        "puesto": "Puesto",
        "area": "Área",
        "campo_requerido": "Campo requerido",
        "nombre_obligatorio": "Debes completar todos los campos obligatorios",
        "iniciando_camara": "Iniciando cámara",
        "preparando_biometria": "Preparando sistema biométrico...",
        "iniciando_camara_estado": "Iniciando cámara...",
        "error_iniciar_camara": "Error al iniciar cámara",
        "pausar": "Pausar",
        "reanudar": "Reanudar",
        "cancelar": "Cancelar",
        "pausado": "Pausado",
        "presiona_reanudar": "Presiona reanudar para continuar",
        "reanudando": "Reanudando...",
        "preparate_postura": "Prepárate para postura:",
        "comenzando_en": "Comenzando en",
        "manten_posicion": "Mantén la posición",
        "capturando": "Capturando",
        "no_detecta_cara": "No se detecta rostro",
        "acercate_iluminacion": "Acércate o mejora la iluminación",
        "sin_cara": "Sin rostro detectado",
        "frontal": "Frontal",
        "izquierda": "Izquierda",
        "derecha": "Derecha",
        "perfil_izquierda": "Perfil Izquierdo",
        "perfil_derecha": "Perfil Derecho",
        "inst_frontal": "Mira directamente al frente",
        "inst_izquierda": "Gira ligeramente a la izquierda",
        "inst_derecha": "Gira ligeramente a la derecha",
        "inst_perfil_izq": "Muestra tu perfil izquierdo",
        "inst_perfil_der": "Muestra tu perfil derecho",
        "postura_completada": "Postura completada",
        "nueva_postura": "Nueva postura:",
        "todas_posturas": "Todas las posturas completadas",
        "guardando_auto": "Guardando automáticamente...",
        "registro_exitoso": "Registro exitoso",
        "fotos_registradas": "Fotos registradas:",
        "error": "Error",
        "error_guardar": "Ocurrió un error al guardar:",
        "fotos_actualizadas": "Fotos actualizadas",
        "se_actualizaron_fotos": "Se actualizaron {} fotos correctamente",
        "registro_intentos": "Registro de todos los intentos de acceso al sistema",
        "limpiar": "Limpiar",
        "accesos": "Accesos",
        "aceptados": "Aceptados",
        "denegados": "Denegados",
        "placeholder_usuario": "Nombre de usuario...",
        "estado": "Estado",
        "todos": "Todos",
        "aceptado": "Aceptado",
        "denegado": "Denegado",
        "registros": "Registros",
        "usuario": "Usuario",
        "fecha_hora": "Fecha y Hora",
        "confianza": "Confianza",
        "umbral": "Umbral",
        "pregunta_limpiar_historial": "¿Estás seguro de que quieres eliminar TODO el historial?\n\nEsta acción no se puede deshacer.",
        "historial_eliminado": "Historial eliminado correctamente.",
        "usuarios_total": "{} usuario{}",
        "distancia_lbph": "Distancia LBPH",
        "error_cargar_datos": "Error al cargar datos: {}",
        "error_cargar_inactivos": "Error al cargar usuarios inactivos: {}",
        "error_eliminar": "No se pudo eliminar: {}",
        "error_captura": "No se pudo iniciar la captura: {}",
        "total": "Total",
        "presentes": "Presentes",
        "aceptados": "Aceptados",
        "denegados": "Denegados",
        "eliminar_usuario_msg": "¿Deseas eliminar al usuario {nombre} {apellido} con rol {rol}?",
        "confirmar_eliminar_definitivo": "¿Seguro que deseas eliminar este usuario definitivamente?",
        "usuario_eliminado_definitivo": "Usuario eliminado definitivamente",
        "error_eliminar_definitivo": "No se pudo eliminar: {}",

        "confirmar_vaciar_papelera": "¿Seguro que deseas vaciar la papelera?",
        "papelera_vaciada": "Papelera vaciada correctamente",
        "error_vaciar_papelera": "No se pudo vaciar: {}",

        "vaciar_papelera": "Vaciar papelera",
        "error_haar": "No se encontró Haar cascade",
        "aplicar": "Aplicar",
        "cerrar": "Cerrar",
        "ok": "OK",
        "no_engine": "Motor de reconocimiento no iniciado",
        "restablecer_auto": "Restablecer a automático",
        "restablecer_ok": "Umbral restablecido al modo automático",
        "restablecer_fail": "No se pudo restablecer el umbral",
        "instalar_opencv": "Instala opencv-data",
        "desc_estudiante": "Alumno registrado",
        "desc_docente": "Profesor registrado",
        "desc_personal": "Personal administrativo",
          # ── General ─────────────────────────
        "salir": "← Salir",
        "inicio": "Inicio",
        "nuevo": "Nuevo Registro",
        "info": "Información Escolar",
        "historial": "Historial de Accesos",
        "pantalla": "Pantalla de Accesos",
        "bienvenida": "Le da la Bienvenida al Sistema",
        "seleccion": "Seleccione una opción del menú para comenzar",

        # ── Botones ─────────────────────────
        "agregar": "➕ Agregar nuevo usuario",
        "iniciar": "▶ Iniciar",
        "detener": "⏹ Detener",
        "guardar": "Guardar",
        "cancelar": "Cancelar",
        "editar": "Editar",
        "eliminar": "Eliminar",
        "confirmar": "Confirmar",

        # ── Cámara ─────────────────────────
        "camara_on": "⬤ Cámara en línea",
        "camara_off": "⬤ Cámara apagada",
        "iniciando_camara": "Iniciando cámara",
        "error_iniciar_camara": "Error al iniciar cámara",

        # ── Estados ─────────────────────────
        "esperando": "Esperando reconocimiento",
        "colocate": "Colócate frente a la cámara",
        "presiona_iniciar": "Presiona ▶ Iniciar para comenzar",

        # ── Roles ─────────────────────────
        "estudiante": "Estudiante",
        "docente": "Docente",
        "personal": "Personal",

        "desc_estudiante": "Alumno registrado en el sistema",
        "desc_docente": "Profesor registrado en el sistema",
        "desc_personal": "Personal administrativo",

        # ── Campos ─────────────────────────
        "nombre": "Nombre",
        "apellido_paterno": "Primer apellido",
        "apellido_materno": "Segundo apellido",
        "matricula": "Número de control",
        "telefono": "Teléfono",
        "correo": "Correo Electrónico",
        "fecha_nacimiento": "Fecha de Nacimiento",
        "tipo_sangre": "Tipo de Sangre",
        "direccion": "Dirección",

        "facultad": "Facultad",
        "carrera": "Carrera",
        "grado": "Grado",
        "grupo": "Grupo",
        "materia": "Materia",
        "puesto": "Puesto",
        "area": "Área",
        "grado_imparte": "Grado que imparte",

        # ── Posturas ─────────────────────────
        "frontal": "Frontal",
        "izquierda": "Izquierda",
        "derecha": "Derecha",
        "perfil_izquierda": "Perfil Izquierdo",
        "perfil_derecha": "Perfil Derecho",

        "inst_frontal": "Mira directamente al frente",
        "inst_izquierda": "Gira ligeramente a la izquierda",
        "inst_derecha": "Gira ligeramente a la derecha",
        "inst_perfil_izq": "Muestra tu perfil izquierdo",
        "inst_perfil_der": "Muestra tu perfil derecho",

        # ── Mensajes ─────────────────────────
        "error": "Error",
        "registro_exitoso": "Registro exitoso",
        "guardando_auto": "Guardando automáticamente...",
        "matricula_min": "El número de control debe tener al menos 6 dígitos",
        "matricula_num": "El número de control solo debe contener números",
        "matricula_longitud": "El número de control debe tener {n} dígitos",
        "correo_invalido": "El correo electrónico no es válido",
        "telefono_num": "El teléfono solo debe contener números",
        "telefono_min": "El teléfono debe tener al menos 10 dígitos",
        "telefono_max": "El teléfono no puede tener más de 13 dígitos",
        "nombre_invalido": "El nombre solo debe contener letras",
        "apellido_invalido": "El apellido solo debe contener letras",
        "campo_min_caracteres": "{campo} debe tener mínimo {min} caracteres",
        "correo_existe": "El correo ya existe",
        "matricula_existe": "La matrícula ya existe",

        # ── Haar / OpenCV ───────────────────
        "error_haar": "No se encontró el archivo Haar cascade",
        "instalar_opencv": "Instala con: sudo apt install opencv-data",
        "confirm_deletion": "Confirmar eliminación",
        "delete_user_msg": "¿Eliminar usuario?",
        "error_deleting_user": "Error al eliminar usuario",
        "confirm_restoration": "Confirmar restauración",
        "restore_user_msg": "¿Restaurar a {nombre}?",
        "error_restaurar": "No se pudo restaurar: {}",
        "ver_detalles": "Ver detalles",
        "ocultar_detalles": "Ocultar detalles",
        "selecciona_usuario": "Selecciona un usuario",
        "detalles": "Detalles",
        "activos": "Activos",
        "inactivos": "Inactivos",
        "procesando_imagenes": "Procesando imágenes biométricas...",
        "sin_rostros": "No se pudieron extraer rostros.",
        "generando_modelo": "Generando modelo LBPH...",
        "sin_usuarios": "No hay usuarios con biometría en la BD",
        "modelo_corrupto": "Modelo corrupto — regenerando...",
        "cerrado": "Sistema cerrado",
        "sin_camara": "No se pudo abrir la cámara",
        "camara_iniciada": "Cámara iniciada",
        "acceso_permitido": "ACCESO PERMITIDO",
        "acceso_denegado": "ACCESO DENEGADO",
        "tolerancia": "Tolerancia",
        "ajustar": "ajustar",
        "salir": "Salir",
        "modelo_listo": "Modelo listo",
        "sin_datos": "Sin datos — registra usuarios primero",
        "desconocido": "Desconocido",
        "volver_formulario": "Volver al formulario",
        "paso_captura": "Paso 2/2 — Captura biométrica automática",
        "postura": "Postura",
        "comenzando_en": "Comenzando en",
        "rostro_borroso": "Rostro borroso",
        "ajusta_iluminacion": "Ajusta la iluminación",
        "desconocido": "Desconocido",
        "usuario": "Usuario",
        "usuario_ya_registrado": "Usuario ya registrado con esa cara",
        "usuario_inactivo_detectado": "Usuario inactivo con esa cara",
        "se_detecto": "Se detectó",
        "pregunta_editar_usuario": "¿Deseas editar su usuario o cancelar el registro?",
        "pregunta_restaurar_usuario": "¿Deseas restaurar su usuario o cancelar el registro?",
        "editar_usuario": "Editar usuario",
        "restaurar_usuario": "Restaurar usuario",
        "cancelar_registro": "Cancelar registro",
        "error_abrir_edicion": "No se pudo abrir la vista de edición",
        "error_edicion": "No se pudo abrir la edición",
        "usuario_restaurado": "Usuario restaurado",
        "usuario_restaurado_mensaje": "El usuario {nombre} fue restaurado correctamente",
        "preparate_para": "Prepárate para",
        "cambiando_en_2s": "cambiando en 2 segundos",
        "fotos": "fotos",
        "repetir": "Repetir",
        "frontal": "Frontal",
        "izquierda": "Izquierda",
        "derecha": "Derecha",
        "perfil_izquierda": "Perfil izquierdo",
        "perfil_derecha": "Perfil derecho",
        "acceso_denegado": "ACCESO DENEGADO",
        "acceso_permitido": "ACCESO PERMITIDO",
        "desconocido": "Desconocido",
        "usuario": "Usuario",
        "confianza": "Confianza",
        "acceso_permitido": "ACCESO PERMITIDO",
        "acceso_denegado": "ACCESO DENEGADO",
        "activos": "Activos",
        "inactivos": "Inactivos",
        "activos": "Activos",
        "iniciando": "Iniciando",
        "alumno": "Alumno",
        "maestro": "Maestro",
        "personal": "Personal",
        "usuario": "Usuario",
        "titulo_sistema": "UnimoraAccess",
        "descripcion_login": "Control de acceso biométrico\npara instituciones educativas",
        "reconocimiento_facial": "Reconocimiento facial",
        "acceso_seguro": "Acceso seguro",
        "historial_entradas": "Historial de entradas",
        "gestion_usuarios": "Gestión de usuarios",
        "acceso_directo": "Acceso directo",
        "subtitulo_login": "Sistema de control\n de acceso institucional",
        "administrador": "Administrador",
        "acceso_total": "Acceso total al sistema",
        "sesion_automatica": "Sesión iniciada automáticamente",
        "entrar_sistema": "Entrar al sistema",
        "usuarios": "Usuarios",
        "precision": "Precisión",
        "activo": "Activo",
        "roles_extra": "Roles extra",
        "alumno": "Alumno",
        "maestro": "Maestro",
        "personal": "Personal",
        "completa_datos_rol": "Completa los datos para el rol",
        "guardar": "Guardar",
        "facultad": "Facultad",
        "carrera": "Carrera",
        "grado": "Grado",
        "grupo": "Grupo",
        "grado_imparte": "Grado que imparte",
        "materia": "Materia",
        "puesto": "Puesto",
        "area": "Área",
                },
    "en": {
        "titulo": "Main Panel",
        "salir": "← Logout",
        "inicio": "Home",
        "nuevo": "New Register",
        "info": "School Info",
        "historial": "Access History",
        "pantalla": "Access Screen",
        "bienvenida": "Welcome to the System",
        "seleccion": "Select an option from the menu",
        "agregar": "➕  Add new user",
        "iniciar": "▶  Start",
        "detener": "⏹  Stop",
        "camara_on": "⬤  Camera online",
        "camara_off": "⬤  Camera off",
        "navegacion": "NAVIGATION",
        "control_accesos": "Access Control",
        "esperando": "Waiting for recognition",
        "colocate": "Stand in front of the camera",
        "presiona_iniciar": "Press ▶ Start to begin",
        "iniciando_camara": "Starting camera",
        "preparando": "Preparing facial recognition...",
        "confirmar_salida": "Confirm exit",
        "seguro_salir": "Are you sure you want to exit?",
        "info_escolar": "School Information",
        "gestion_usuarios": "Management of registered users in the system",
        "ver_detalles": "View details",
        "buscar": "Search:",
        "placeholder_busqueda": "Name, ID or major...",
        "usuarios_registrados": "Registered users",
        "nombre_completo": "Full Name",
        "matricula": "Control ID",
        "rol": "Role",
        "editar": "Edit",
        "eliminar": "Delete",
        "error": "Error",
        "error_db": "Could not connect to the database",
        "detalles": "Details",
        "detalles_acceso": "Access details",
        "selecciona_usuario": "Select a user",
        "atencion": "Warning",
        "editar_usuario": "Edit User",
        "datos_personales": "Personal Information",
        "guardar": "Save",
        "retomar_fotos": "Retake photos",
        "cancelar": "Cancel",
        "confirmar_eliminacion": "Confirm deletion",
        "papelera": "User Trash",
        "papelera_usuarios": "Trash — Inactive Users",
        "restaurar_usuario": "Restore User",
        "ocultar_detalles": "Hide details",
        "nombre": "Name",
        "apellido_paterno": "Last Name",
        "apellido_materno": "Second Last Name",
        "telefono": "Phone",
        "facultad": "Faculty",
        "carrera": "Major",
        "grado": "Grade",
        "grupo": "Group",
        "materia": "Subject",
        "puesto": "Position",
        "area": "Area",
        "grado_imparte": "Grade taught",
        "info_academica": "Academic Information",
        "info_docente": "Teacher Information",
        "info_laboral": "Work Information",
        "campos_obligatorios": "Required fields",
        "error_nombre": "Name and last name are required",
        "actualizado": "Updated",
        "usuario_actualizado": "User updated successfully",
        "no_actualizar": "Could not update",
        "eliminado": "Deleted",
        "usuario_eliminado": "User deleted successfully",
        "confirmar": "Confirm",
        "pregunta_eliminar": "Delete {nombre} ({rol})?",
        "pregunta_restaurar": "Restore this user?",
        "restaurado": "Restored",
        "usuario_restaurado": "User restored successfully",
        "estudiante": "Student",
        "docente": "Teacher",
        "personal": "Staff",
        "nuevo_registro_titulo": "New Registration",
        "selecciona_tipo_usuario": "Select user type",
        "seleccionar": "Select",
        "regresar": "Back",
        "paso_datos": "Step 1: Data Entry",
        "continuar_fotos": "Continue to Photos",
        "datos_personales": "Personal Information",
        "info_academica": "Academic Information",
        "info_docente": "Teacher Information",
        "info_laboral": "Work Information",
        "nombre": "First Name",
        "apellido_paterno": "Last Name",
        "apellido_materno": "Second Last Name",
        "matricula": "Control ID",
        "telefono": "Phone Number",
        "correo": "Email Address",
        "grado": "Grade",
        "grupo": "Group",
        "facultad": "Faculty",
        "carrera": "Major",
        "grado_imparte": "Grade Taught",
        "materia": "Subject",
        "puesto": "Position",
        "area": "Area",
        "campo_requerido": "Required field",
        "nombre_obligatorio": "You must complete all required fields",
        "iniciando_camara": "Starting camera",
        "preparando_biometria": "Preparing biometric system...",
        "iniciando_camara_estado": "Starting camera...",
        "error_iniciar_camara": "Error starting camera",
        "pausar": "Pause",
        "reanudar": "Resume",
        "cancelar": "Cancel",
        "pausado": "Paused",
        "presiona_reanudar": "Press resume to continue",
        "reanudando": "Resuming...",
        "preparate_postura": "Get ready for pose:",
        "comenzando_en": "Starting in",
        "manten_posicion": "Hold position",
        "capturando": "Capturing",
        "no_detecta_cara": "Face not detected",
        "acercate_iluminacion": "Move closer or improve lighting",
        "sin_cara": "No face detected",
        "frontal": "Front",
        "izquierda": "Left",
        "derecha": "Right",
        "perfil_izquierda": "Left Profile",
        "perfil_derecha": "Right Profile",
        "inst_frontal": "Look straight ahead",
        "inst_izquierda": "Turn slightly left",
        "inst_derecha": "Turn slightly right",
        "inst_perfil_izq": "Show your left profile",
        "inst_perfil_der": "Show your right profile",
        "postura_completada": "Pose completed",
        "nueva_postura": "New pose:",
        "todas_posturas": "All poses completed",
        "guardando_auto": "Saving automatically...",
        "registro_exitoso": "Successful registration",
        "fotos_registradas": "Registered photos:",
        "error": "Error",
        "error_guardar": "An error occurred while saving:",
        "fotos_actualizadas": "Photos updated",
        "se_actualizaron_fotos": "{} photos were updated successfully",
        "registro_intentos": "Record of all system access attempts",
        "limpiar": "Clear",
        "accesos": "Accesses",
        "aceptados": "Accepted",
        "denegados": "Denied",
        "placeholder_usuario": "Username...",
        "estado": "Status",
        "todos": "All",
        "aceptado": "Accepted",
        "denegado": "Denied",
        "registros": "Records",
        "usuario": "User",
        "fecha_hora": "Date and Time",
        "confianza": "Confidence",
        "umbral": "Threshold",
        "pregunta_limpiar_historial": "Are you sure you want to delete ALL history?\n\nThis action cannot be undone.",
        "historial_eliminado": "History deleted successfully.",
        "usuarios_total": "{} user{}",
        "distancia_lbph": "LBPH distance",
        "error_cargar_datos": "Error loading data: {}",
        "error_cargar_inactivos": "Error loading inactive users: {}",
        "error_eliminar": "Could not delete: {}",
        "error_captura": "Could not start capture: {}",
        "total": "Total",
        "presentes": "Present",
        "aceptados": "Accepted",
        "denegados": "Denied",
        "eliminar_usuario_msg": "Do you want to delete user {nombre} {apellido} with role {rol}?",
        "confirmar_eliminar_definitivo": "Are you sure you want to permanently delete this user?",
        "usuario_eliminado_definitivo": "User permanently deleted",
        "error_eliminar_definitivo": "Could not delete: {}",

        "confirmar_vaciar_papelera": "Are you sure you want to empty the trash?",
        "papelera_vaciada": "Trash emptied successfully",
        "error_vaciar_papelera": "Could not empty trash: {}",

        "vaciar_papelera": "Empty trash",
        "error_haar": "Haar cascade not found",
        "aplicar": "Apply",
        "cerrar": "Close",
        "ok": "OK",
        "no_engine": "Recognition engine not started",
        "restablecer_auto": "Reset to automatic",
        "restablecer_ok": "Threshold reset to automatic",
        "restablecer_fail": "Could not reset threshold",
        "instalar_opencv": "Install opencv-data",
        "desc_estudiante": "Registered student",
        "desc_docente": "Registered teacher",
        "desc_personal": "Administrative staff",
                # ── General ─────────────────────────
        "salir": "← Logout",
        "inicio": "Home",
        "nuevo": "New Register",
        "info": "School Info",
        "historial": "Access History",
        "pantalla": "Access Screen",
        "bienvenida": "Welcome to the System",
        "seleccion": "Select an option from the menu",

        # ── Botones ─────────────────────────
        "agregar": "➕ Add new user",
        "iniciar": "▶ Start",
        "detener": "⏹ Stop",
        "guardar": "Save",
        "cancelar": "Cancel",
        "editar": "Edit",
        "eliminar": "Delete",
        "confirmar": "Confirm",

        # ── Cámara ─────────────────────────
        "camara_on": "⬤ Camera online",
        "camara_off": "⬤ Camera off",
        "iniciando_camara": "Starting camera",
        "error_iniciar_camara": "Error starting camera",

        # ── Estados ─────────────────────────
        "esperando": "Waiting for recognition",
        "colocate": "Stand in front of the camera",
        "presiona_iniciar": "Press ▶ Start to begin",

        # ── Roles ─────────────────────────
        "estudiante": "Student",
        "docente": "Teacher",
        "personal": "Staff",

        "desc_estudiante": "Student registered in the system",
        "desc_docente": "Teacher registered in the system",
        "desc_personal": "Administrative staff",

        # ── Campos ─────────────────────────
        "nombre": "First Name",
        "apellido_paterno": "Last Name",
        "apellido_materno": "Second Last Name",
        "matricula": "Control ID",
        "telefono": "Phone",
        "correo": "Email",
        "fecha_nacimiento": "Birth Date",
        "tipo_sangre": "Blood Type",
        "direccion": "Address",

        "facultad": "Faculty",
        "carrera": "Major",
        "grado": "Grade",
        "grupo": "Group",
        "materia": "Subject",
        "puesto": "Position",
        "area": "Area",
        "grado_imparte": "Grade taught",

        # ── Posturas ─────────────────────────
        "frontal": "Front",
        "izquierda": "Left",
        "derecha": "Right",
        "perfil_izquierda": "Left Profile",
        "perfil_derecha": "Right Profile",

        "inst_frontal": "Look straight ahead",
        "inst_izquierda": "Turn slightly left",
        "inst_derecha": "Turn slightly right",
        "inst_perfil_izq": "Show your left profile",
        "inst_perfil_der": "Show your right profile",

        # ── Mensajes ─────────────────────────
        "error": "Error",
        "registro_exitoso": "Successful registration",
        "guardando_auto": "Saving automatically...",
        "matricula_min": "Control ID must be at least 6 digits",
        "matricula_num": "Control ID must contain only numbers",
        "matricula_longitud": "Control ID must have {n} digits",
        "correo_invalido": "Invalid email address",
        "telefono_num": "Phone number must contain only numbers",
        "telefono_min": "Phone number must have at least 10 digits",
        "telefono_max": "Phone number cannot have more than 13 digits",
        "nombre_invalido": "Name must contain only letters",
        "apellido_invalido": "Last name must contain only letters",
        "campo_min_caracteres": "{campo} must have at least {min} characters",
        "correo_existe": "Email already exists",
        "matricula_existe": "Control ID already exists",


        # ── Haar / OpenCV ───────────────────
        "error_haar": "Haar cascade file not found",
        "instalar_opencv": "Install with: sudo apt install opencv-data",
        "confirm_deletion": "Confirm deletion",
        "delete_user_msg": "Delete user?",
        "error_deleting_user": "Error deleting user",
        "confirm_restoration": "Confirm restoration",
        "restore_user_msg": "Restore {nombre}?",
        "error_restaurar": "Could not restore: {}",
        "view_details": "View details",
        "hide_details": "Hide details",
        "select_user": "Select a user",
        "details": "Details",
        "active": "Active",
        "inactive": "Inactive",
         "procesando_imagenes": "Processing biometric images...",
        "sin_rostros": "No faces could be extracted.",
        "generando_modelo": "Generating LBPH model...",
        "sin_usuarios": "No users with biometrics in DB",
        "modelo_corrupto": "Corrupt model — regenerating...",
        "cerrado": "System closed",
        "sin_camara": "Could not open camera",
        "camara_iniciada": "Camera started",
        "acceso_permitido": "ACCESS GRANTED",
        "acceso_denegado": "ACCESS DENIED",
        "tolerancia": "Tolerance",
        "ajustar": "adjust",
        "salir": "Quit",
        "modelo_listo": "Model ready",
        "sin_datos": "No data — register users first",
        "desconocido": "Unknown",
        "volver_formulario": "Back to form",
        "paso_captura": "Step 2/2 — Automatic biometric capture",
        "postura": "Posture",
        "comenzando_en": "Starting in",
        "rostro_borroso": "Blurry face",
        "ajusta_iluminacion": "Adjust lighting",
        "desconocido": "Unknown",
        "usuario": "User",
        "usuario_ya_registrado": "User already registered with this face",
        "usuario_inactivo_detectado": "Inactive user detected with this face",
        "se_detecto": "Detected",
        "pregunta_editar_usuario": "Do you want to edit this user or cancel the registration?",
        "pregunta_restaurar_usuario": "Do you want to restore this user or cancel the registration?",
        "editar_usuario": "Edit user",
        "restaurar_usuario": "Restore user",
        "cancelar_registro": "Cancel registration",
        "error_abrir_edicion": "Could not open edit view",
        "error_edicion": "Could not open edit",
        "usuario_restaurado": "User restored",
        "usuario_restaurado_mensaje": "User {nombre} was restored successfully",
        "preparate_para": "Get ready for",
        "cambiando_en_2s": "switching in 2 seconds",
        "fotos": "photos",
        "repetir": "Repeat",
        "inst_frontal": "Mira directamente a la cámara",
        "inst_izquierda": "Gira ligeramente a la izquierda",
        "inst_derecha": "Gira ligeramente a la derecha",
        "inst_perfil_izq": "Muestra tu perfil izquierdo",
        "inst_perfil_der": "Muestra tu perfil derecho",
        "acceso_denegado": "ACCESS DENIED",
        "acceso_permitido": "ACCESS GRANTED",
        "desconocido": "Unknown",
        "usuario": "User",
        "confianza": "Confidence",
        "acceso_permitido": "ACCESS GRANTED",
        "acceso_denegado": "ACCESS DENIED",
        "activos": "Active",
        "inactivos": "Inactive",
        "activos": "Active",
        "iniciando": "Starting",
        "alumno": "Student",
        "maestro": "Teacher",
        "personal": "Staff",
        "usuario": "User",
        "titulo_sistema": "UnimoraAccess",
        "descripcion_login": "Biometric access control\nfor educational institutions",
        "reconocimiento_facial": "Facial recognition",
        "acceso_seguro": "Secure access",
        "historial_entradas": "Entry history",
        "gestion_usuarios": "User management",
        "acceso_directo": "Quick access",
        "subtitulo_login": "Institutional access\ncontrol system",
        "administrador": "Administrator",
        "acceso_total": "Full system access",
        "sesion_automatica": "Session started automatically",
        "entrar_sistema": "Enter system",
        "usuarios": "Users",
        "precision": "Accuracy",
        "activo": "Active",
        "roles_extra": "Extra roles",
        "alumno": "Student",
        "maestro": "Teacher",
        "personal": "Staff",
        "completa_datos_rol": "Complete the data for the role",
        "guardar": "Save",
        "facultad": "Faculty",
        "carrera": "Career",
        "grado": "Grade",
        "grupo": "Group",
        "grado_imparte": "Grade taught",
        "materia": "Subject",
        "puesto": "Position",
        "area": "Area",
            }
    }

def t(clave):
    return TEXTOS[IDIOMA_ACTUAL].get(clave, clave)

# ─────────────────────────────────────────────────────────────────────────────
# OBTENER IDIOMA ACTUAL
# ─────────────────────────────────────────────────────────────────────────────

def idioma_actual():
    return IDIOMA_ACTUAL


# ─────────────────────────────────────────────────────────────────────────────
# CAMBIAR IDIOMA
# ─────────────────────────────────────────────────────────────────────────────

def cambiar_idioma(nuevo_idioma=None):

    global IDIOMA_ACTUAL

    # Si no se manda idioma, alterna automáticamente
    if nuevo_idioma is None:
        IDIOMA_ACTUAL = "en" if IDIOMA_ACTUAL == "es" else "es"
        return

    # Si sí se manda idioma específico
    if nuevo_idioma in TEXTOS:
        IDIOMA_ACTUAL = nuevo_idioma